spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.181.87.125/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wx5772d32ecf748e4f
  mpAppSecret: 9e645f9ce6ccf4a6969a0d2ffa603d32

