spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.181.87.125/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.181.87.125
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx5772d32ecf748e4f
  mpAppSecret: 9e645f9ce6ccf4a6969a0d2ffa603d32
  #无效
  openAppId: wx5772d32ecf748e4f
  openAppSecret: 9e645f9ce6ccf4a6969a0d2ffa603d32
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sellalot.nat300.top/sell/pay/notify
  #模板消息配置
  templateId:
    orderStatus:

projectUrl:
  wechatMpAuthorize: http://sellalot.nat300.top
  wechatOpenAuthorize: http://sellalot.nat300.top
  sell: http://sellalot.nat300.top


#mybatis记录其sql语句,开发环境使用，生产环境不使用
logging:
  level:
    com.xjtu.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*
